service: govhack

plugins:
  - serverless-webpack
  
# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  webpack: ./webpack.config.js

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:

  calculatePatentState:
    handler: handler.calculatePatentState
    events:
      - http:
          path: patent
          method: post
          timeout: 60 # timeout after a minute to avoid issues
      - http:
          path: patent
          method: put
          timeout: 60 # timeout after a minute to avoid issues

  calculateTrademarkState:
    handler: handler.calculateTrademarkState
    events:
      - http:
          path: trademark
          method: post
          timeout: 60 # timeout after a minute to avoid issues
      - http:
          path: trademark
          method: put
          timeout: 60 # timeout after a minute to avoid issues

